# Generated by Django 5.1 on 2024-08-31 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['created'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['full_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
