# Generated by Django 5.1 on 2024-09-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_files_options_alter_users_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='path_to_file',
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.users'),
        ),
    ]
