# Generated by Django 5.1 on 2024-09-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_files_path_to_file_files_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='path_to_user',
        ),
    ]
