# Generated by Django 5.1 on 2024-09-06 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_users_path_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 10, 5, 12, 489161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='files',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
