# Generated by Django 5.1 on 2024-09-13 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_files_comment_files_last_download_files_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image',
            field=models.ImageField(default='', upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 15, 11, 2, 738507, tzinfo=datetime.timezone.utc)),
        ),
    ]
