# Generated by Django 5.1 on 2024-09-14 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_files_image_alter_files_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(default='', upload_to='storage_files'),
        ),
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 16, 59, 30, 500213, tzinfo=datetime.timezone.utc)),
        ),
    ]
