# Generated by Django 5.1 on 2024-09-17 14:35

import datetime
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(default='', upload_to=storage.models.user_path),
        ),
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.date(2024, 9, 17)),
        ),
    ]
