# Generated by Django 5.1 on 2024-09-24 10:36

import datetime
import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_files_image_alter_files_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.FileField(default='', upload_to=storage.models.user_path),
        ),
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.date(2024, 9, 24)),
        ),
    ]
