# Generated by Django 5.1 on 2024-09-25 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_files_image_alter_files_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
