# Generated by Django 5.1 on 2024-09-26 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_alter_files_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateField(default=datetime.date(2024, 9, 26)),
        ),
    ]
