# Generated by Django 5.1 on 2024-09-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_alter_files_last_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='last_download',
            field=models.DateTimeField(null=True),
        ),
    ]
