# Generated by Django 5.1 on 2024-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_files_last_download'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='files',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
